name: ANALISE-DE-QUALIDADE-SONAR-CLOUD-PR

on:
  pull_request:
    types: [opened, synchronize, reopened] # Eventos explícitos
    branches: 
      - develop

jobs:
  build-and-analyse:
    name: Compilar, Testar e Analisar
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Instalar Java 17 (requisito para SonarCloud)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Instalar dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Instalar SonarScanner para .NET
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Compilar e Analisar com SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      run: |
          dotnet-sonarscanner begin \
            /k:"toledodouglas_devops-training" \
            /o:"toledodouglas" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      
    - name: Restaurar Pacotes(.NET)
      run: dotnet restore src/MeuProjeto.sln

    - name: Compilar Código (.NET)
      run: dotnet build src/MeuProjeto.sln --configuration Release --no-restore

    - name: Testar Código (.NET)
      run: dotnet test src/MeuProjeto.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

    - name: Converter Relatório de Cobertura
      run: cp TestResults/*/coverage.cobertura.xml coverage.xml || true

    - name: Finalizar Análise do SonarCloud e enviar resultados
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet-sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}