name: DEPLOY DEV 

on: 
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    name: Provisionar e Lançar (DEV)
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurar dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Compilar Artefato (.NET Publish)
      run: dotnet publish ./src/backend/Api.csproj --configuration Release --output ${{ github.workspace }}/app-publish

    - name: Login Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Plan
      working-directory: ./infra
      run: terraform plan -var-file="ambientes/dev.tfvars"

    - name: Terraform Apply (DEV)
      env: 
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      working-directory: ./infra
      run: terraform apply -var-file="ambientes/dev.tfvars" -auto-approve

    - name: Deploy para Azure App Service (DEV)
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-devops-training-dev-toledo'
        package: '${{ github.workspace }}/app-publish'